# Generated by Django 6.0.5 on 2026-05-16 05:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='DEMO METCA', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='college/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='college/')),
                ('about_text', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='college/')),
                ('established_year', models.CharField(blank=True, max_length=10)),
                ('affiliation', models.CharField(blank=True, max_length=300)),
                ('accreditation', models.CharField(blank=True, max_length=300)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'College Settings',
                'verbose_name_plural': 'College Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_name', models.CharField(help_text='e.g. B.Ed, M.Ed', max_length=50)),
                ('description', models.TextField()),
                ('duration', models.CharField(choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years')], default='2 Years', max_length=20)),
                ('seats', models.PositiveIntegerField(default=50)),
                ('eligibility', models.TextField(help_text='Who can apply?')),
                ('fee_per_year', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('highlights', models.TextField(blank=True, help_text='One highlight per line')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(choices=[('Principal', 'Principal'), ('Vice Principal', 'Vice Principal'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Guest Lecturer', 'Guest Lecturer'), ('Administrative', 'Administrative Staff')], max_length=50)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('qualification', models.CharField(help_text='e.g. M.Ed, Ph.D', max_length=300)),
                ('experience', models.CharField(blank=True, help_text='e.g. 12 years', max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=300)),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Faculty Member',
                'verbose_name_plural': 'Faculty',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FounderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Founder', 'Founder'), ('Co-Founder', 'Co-Founder'), ('Chairman', 'Chairman'), ('Vice Chairman', 'Vice Chairman'), ('Secretary', 'Secretary'), ('Principal', 'Principal'), ('Director', 'Director'), ('Managing Trustee', 'Managing Trustee')], max_length=30)),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='founders/')),
                ('signature', models.ImageField(blank=True, help_text='Optional signature image', null=True, upload_to='founders/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Founder / Management Message',
                'verbose_name_plural': 'Founder / Management Messages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('general', 'General'), ('admission', 'Admission'), ('exam', 'Examination'), ('event', 'Event'), ('result', 'Result'), ('holiday', 'Holiday'), ('urgent', 'Urgent')], default='general', max_length=20)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, help_text='Optional PDF or image', null=True, upload_to='notices/')),
                ('is_urgent', models.BooleanField(default=False, help_text='Shows a red badge')),
                ('is_active', models.BooleanField(default=True)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, help_text='Hide after this date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, help_text='e.g. General, OBC, SC, ST', max_length=50)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('academic_year', models.CharField(help_text='e.g. 2025-26', max_length=20)),
                ('tenth_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='10th %')),
                ('twelfth_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='12th %')),
                ('degree_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Degree %')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='admissions/photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlist', 'Waitlist')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not shown to applicant)')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('course_applied', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='main.course')),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='main.gallerycategory')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
